=== AdamKrajcik/PB029/2_zapoctovy_priklad/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="people">
		<xsd:complexType>
			<xsd:choice >
				<xsd:element name="person" type="person-type" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:complexType name="person-type">
		<xsd:sequence>
			<xsd:element name="firstname" type="name-type"/>
			<xsd:element name="lastname" type="name-type"/>
			<xsd:element name="email" type="extended-email-type" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="phone" type="extended-phone-type" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="link" type="extended-link-type" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="other" type="other-type" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="address" type="address-type" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="note" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="name-type">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="30"/>
			<xsd:pattern value="[\w \-]+"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="address-type">
		<xsd:sequence>
			<xsd:element name="street" type="street-type"/>
			<xsd:element name="number" type="number-type"/>
			<xsd:element name="postCode" type="postCode-type"/>
			<xsd:element name="city" type="city-type"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="other-type">
		<xsd:sequence>
			<xsd:element name="service" type="service-type"/>
			<xsd:element name="id" type="id-type"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="contact-type">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="osobní"/>
			<xsd:enumeration value="pracovní"/>
			<xsd:enumeration value="jiná"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="basic-phone-type">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[\d ]+[\d]"/>
			<xsd:maxLength value="20"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="basic-link-type">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[^ ]+"/>
			<xsd:maxLength value="3000"/>
		</xsd:restriction>
	</xsd:simpleType>


	<xsd:simpleType name="basic-email-type">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[^@]{1,64}@[^@]{1,63}"/>
		</xsd:restriction>
	</xsd:simpleType>
	
		<xsd:simpleType name="service-type">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[\w]+"/>
			<xsd:maxLength value="32"/>
		</xsd:restriction>
	</xsd:simpleType>
	
		<xsd:simpleType name="id-type">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[^ ]+"/>
			<xsd:maxLength value="64"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:complexType name="extended-email-type">
		<xsd:simpleContent>
			<xsd:extension base="basic-email-type">
				<xsd:attribute name="type" type="contact-type"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	
	<xsd:complexType name="extended-phone-type">
		<xsd:simpleContent>
			<xsd:extension base="basic-phone-type">
				<xsd:attribute name="type" type="contact-type"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	
	<xsd:complexType name="extended-link-type">
		<xsd:simpleContent>
			<xsd:extension base="basic-link-type">
				<xsd:attribute name="type" type="contact-type"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	
	<xsd:simpleType name="street-type">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[\w\.\- ]+"/>
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="number-type">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[0-9]+[a-zA-Z]*"/>
			<xsd:maxLength value="10"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="city-type">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[\w\.\- ]+"/>
			<xsd:maxLength value="50"/>
		</xsd:restriction>
	</xsd:simpleType>
	
		<xsd:simpleType name="postCode-type">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[0-9]+"/>
			<xsd:maxLength value="10"/>
		</xsd:restriction>
	</xsd:simpleType>
	
</xsd:schema>

=== AdamKrajcik/PB029/2_zapoctovy_priklad/valid-real-world-records.xml
<?xml version="1.0" encoding="UTF-8"?>
<people xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./schema.xsd">
	<person>
		<firstname>Janko</firstname>
		<lastname>Kráľ</lastname>
		<email type="osobní">janko555@gmail.com</email>
		<phone type="pracovní">00421 915 651 818</phone>
		<address>
			<street>Slamkova</street>
			<number>5</number>
			<postCode>94907</postCode>
			<city>Nitra</city>
		</address>
	</person>
	<person>
		<firstname>Jozef</firstname>
		<lastname>Mrkva</lastname>
		<email>jozko.mrkva@gmail.com</email>
	</person>
	<person>
		<firstname>Adam</firstname>
		<lastname>Šangala</lastname>
		<address>
			<street>Slamkova</street>
			<number>5</number>
			<postCode>94907</postCode>
			<city>Nitra</city>
		</address>
		<note>Pozn8mka na jeden riadok.
		</note>
	</person>
	<person>
		<firstname>Martin</firstname>
		<lastname>Krt</lastname>
		<phone>00421 915 651 818</phone>
	</person>
	<person>
		<firstname>Edna</firstname>
		<lastname>Módna</lastname>
		<link type="jiná">www.google.sk</link>
	</person>
</people>

=== AdamKrajcik/PB029/2_zapoctovy_priklad/valid-full-record.xml
<?xml version="1.0" encoding="UTF-8"?>
<people xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema.xsd">
	<person>
		<firstname>Jozef</firstname>
		<lastname>Mrkva</lastname>
		<email>jozko.mrkva@gmail.com</email>
		<email type="osobní">jozko.mrkva@gmail.com</email>
		<phone>00421 915 651 818</phone>
		<phone type="pracovní">00421 559 854 478</phone>
		<link >www.dunco.sk</link>
		<link type="jiná">www.google.sk</link>
		<other>
			<service>Skype</service>
			<id>StratilSomPsa</id>
		</other>
		<address>
			<street>Slamkova</street>
			<number>5</number>
			<postCode>94907</postCode>
			<city>Nitra</city>
		</address>
		<note>Pozn8mka na
		
				viacero 
				riadkov.
		</note>
		<note>Pozn8mka na jeden riadok.
		</note>
	</person>
</people>
